name: agrifrontend
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/crops.jpg
    - assets/pests.jpg
    - assets/weeds.jpg
    - assets/logo.jpg

flutter_native_splash:
  color: "#ffffff" # Background color of your splash screen
  image: assets/logo.jpg # Path to your splash image
  android: true
  ios: true
  web: true
  android_gravity: fill # How the image should be positioned
